name: 'Terraform Workflow Dispatch'

on:
  workflow_dispatch:
    inputs:
      terraform_operation:
        description: "Terraform operation: plan, apply, destroy"
        required: true
        default: "plan"
        type: choice
        options:
          - plan
          - apply
          - destroy

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

env:
  GOOGLE_PROJECT: "${{ secrets.GOOGLE_PROJECT }}"
  GOOGLE_OAUTH_ACCESS_TOKEN: "${{ secrets.GOOGLE_OAUTH_ACCESS_TOKEN }}"
  TF_VAR_IMPERSONATE_SERVICE_ACCOUNT_EMAIL: "${{ secrets.IMPERSONATE_SERVICE_ACCOUNT_EMAIL }}"

jobs:
  terraform-dispatch-read:
    name: Terraform Read Privilege Job
    if: "${{ github.event.act || github.event.inputs.terraform_operation == 'plan' }}"
    runs-on: ubuntu-latest
      
    defaults:
      run:
        working-directory: "./test"
        
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Configure GCP Credentials - Github Runner
        uses: 'google-github-actions/auth@v2'
        if: ${{ !github.event.act }}
        with:
          service_account: "${{ secrets.impersonate_service_account_email }}"
          workload_identity_provider: "${{ secrets.workload_identity_provider }}"
  
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
  
      - name: Terraform init
        run: terraform init
  
      - name: Terraform plan
        run: terraform plan
    
  terraform-dispatch-write:
    name: Terraform Write Privilege Job
    environment: production
    if: "${{ github.event.act || github.event.inputs.terraform_operation == 'apply' || github.event.inputs.terraform_operation == 'destroy' }}"
    runs-on: ubuntu-latest
      
    defaults:
      run:
        working-directory: "./test"
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure GCP Credentials - Github Runner
        uses: 'google-github-actions/auth@v2'
        if: ${{ !github.event.act }}
        with:
          service_account: "${{ secrets.impersonate_service_account_email }}"
          workload_identity_provider: "${{ secrets.workload_identity_provider }}"
  
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        
      - name: Terraform init
        run: terraform init

      - name: Terraform apply
        if: "${{ github.event.act || github.event.inputs.terraform_operation == 'apply' }}"
        run: terraform apply --auto-approve
  
      - name: Terraform destroy
        if: "${{ github.event.act || github.event.inputs.terraform_operation == 'destroy' }}"
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 3
          retry_on: error
          command: 'terraform -chdir=test destroy --auto-approve'
