name: 'Terraform Workflow Dispatch'

on:
  workflow_dispatch:
    inputs:
      terraform_operation:
        description: "Terraform operation: plan, apply, destroy"
        required: true
        default: "plan"
        type: choice
        options:
          - plan
          - apply
          - destroy

jobs:
  terraform-dispatch-plan:
    if: ${{ github.event.act || github.event.inputs.terraform_operation == 'plan' }}
    uses: ./.github/workflows/reusable/dispatch/tf-read-plan.yml
    secrets: inherit
    with:
      ACT_MODE: ${{ !!github.event.act }}
  
  terraform-dispatch-apply:
    if: ${{ github.event.act ||github.event.inputs.terraform_operation == 'apply' }}
    uses: ./.github/workflows/reusable/dispatch/tf-write-apply.yml
    secrets: inherit
    with:
      ACT_MODE: ${{ !!github.event.act }}

  terraform-dispatch-destroy:
    if: ${{ github.event.act ||github.event.inputs.terraform_operation == 'destroy' }}
    uses: ./.github/workflows/reusable/dispatch/tf-write-destroy.yml
    secrets: inherit
    with:
      ACT_MODE: ${{ !!github.event.act }}
