# Original Work: https://github.com/Azure-Samples/terraform-github-actions/blob/main/.github/workflows/tf-plan-apply.yml

name: 'Terraform Integration Test'

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_run:
    workflows: ["README Workflow Dispatch"]
    types:
      - completed

jobs:
  terraform-integration-plan:
    if: github.actor != 'github-actions[bot]'
    uses: ./.github/workflows/reusable/integration/tf-plan.yml
    secrets: inherit
    with:
      ACT_MODE: ${{ !!github.event.act }}
   
  terraform-integration-apply:
    if: github.event.act || github.ref == 'refs/heads/main'
    needs: [ terraform-integration-plan ]
    uses: ./.github/workflows/reusable/integration/tf-apply.yml
    secrets: inherit
    with:
      ACT_MODE: ${{ !!github.event.act }}
      TF_PLAN_PATH: "${{ needs.terraform-integration-plan.outputs.TF_PLAN_PATH }}"
      TF_PLAN_NAME: "${{ needs.terraform-integration-plan.outputs.TF_PLAN_NAME }}"
                
  terraform-integration-destroy:
    if: always()
    needs: [ terraform-integration-apply]
    uses: ./.github/workflows/reusable/integration/tf-destroy.yml
    secrets: inherit
    with:
      ACT_MODE: ${{ !!github.event.act }}
    