# Original work: https://github.com/Azure-Samples/terraform-github-actions/blob/main/.github/workflows/tf-unit-tests.yml

name: 'Terraform Unit Tests'

on:
  push:

jobs:
  terraform-unit-tests:
    uses: ./.github/workflows/reusable/unit-test/tf-unit-test.yml
    name: 'Terraform Unit Tests'
    secrets: inherit
    with:
      ACT_MODE: ${{ !!github.event.act }}
    